name: Rust

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "main" ]
      
env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Add Target
      run: rustup target add x86_64-unknown-linux-musl
    - name: Install Dependencies
      run: sudo apt install musl-tools
    - name: Cache Rust Dependencies
      uses: Swatinem/rust-cache@v2
    - name: Build
      run: cargo build --release --target x86_64-unknown-linux-musl
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: target/x86_64-unknown-linux-musl/release/ha_ldap_auth
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
